version: 2

project_name: organizer

before:
  hooks:
    - go mod tidy

builds:
  - id: organizer
    main: ./cmd/organizer
    binary: organizer
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - id: default
    builds:
      - organizer
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: Saisathvik94
    name: organizer
