project_name: organizer

before:
  hooks:
    - go mod tidy

builds:
  - id: organizer
    main: ./cmd/organizer/main.go
    binary: organizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: organizer-archive
    format: zip
    name_template: >
      organizer_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - install.sh
      - install.ps1

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: Saisathvik94
    name: organizer
