version: 2

project_name: organizer
release:
  github:
    owner: Saisathvik94
    name: organizer
builds:
  - id: organizer
    main: ./cmd/main.go        # entrypoint
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
    binary: organizer          # Use 'organizer' for all OS; Windows installer will append .exe
archives:
  - format: zip
    replacements:
      darwin: macos
      windows: win
    files:
      - install.ps1
      - install.sh
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
changelog:
  sort: asc
snapshot:
  name_template: "{{ .Tag }}"
