version: 2

project_name: organizer

release:
  github:
    owner: Saisathvik94
    name: organizer

builds:
  - id: organizer
    main: ./cmd/main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
    binary: organizer

archives:
  - format: zip
    name_template: >
      {{ .ProjectName }}_{{ .Tag }}_{{ if eq .Os "darwin" }}macos{{ else if eq .Os "windows" }}windows{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc

snapshot:
  name_template: "{{ .Tag }}-snapshot"
