version: 2

project_name: organizer

release:
  github:
    owner: Saisathvik94
    name: organizer

builds:
  - id: organizer
    main: ./cmd/main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
    binary: organizer    # Same binary name for all OS

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macos{{ else if eq .Os "windows" }}win{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    files:
      - install.ps1
      - install.sh

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc

snapshot:
  name_template: "{{ .Tag }}"

