version: 2

project_name: organizer

before:
  hooks:
    - go mod tidy

builds:
  - id: organizer
    main: ./cmd
    binary: organizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

archives:
  - id: organizer
    builds:
      - organizer
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt

release:
  github:
    owner: sai-sathvik
    name: organizer
  draft: false
  prerelease: false

changelog:
  sort: asc
